"""cambios

Revision ID: 28608bdd888f
Revises: 
Create Date: 2026-07-24 17:26:48.486510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28608bdd888f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id_banco', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_banco')
    )
    op.create_table('contactosemergencia',
    sa.Column('id_contacto', sa.Integer(), nullable=False),
    sa.Column('numero_telefonico', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_contacto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('choferes',
    sa.Column('id_chofer', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('saldo_pendiente', sa.Float(), nullable=True),
    sa.Column('estado_chofer', sa.Enum('DISPONIBLE', 'EN_VIAJE', 'DESCONECTADO', name='estadochofer'), nullable=True),
    sa.ForeignKeyConstraint(['id_chofer'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chofer')
    )
    op.create_table('pasajeros',
    sa.Column('id_pasajero', sa.Integer(), nullable=False),
    sa.Column('saldo_disponible', sa.Float(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_pasajero'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pasajero')
    )
    op.create_table('agendacontactos',
    sa.Column('id_agenda', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('id_contacto', sa.Integer(), nullable=True),
    sa.Column('nombre_contacto', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.ForeignKeyConstraint(['id_contacto'], ['contactosemergencia.id_contacto'], ),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    op.create_table('datosbancarios',
    sa.Column('id_datos', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('id_banco', sa.Integer(), nullable=True),
    sa.Column('numero_cuenta', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id_banco'], ),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.PrimaryKeyConstraint('id_datos'),
    sa.UniqueConstraint('numero_cuenta')
    )
    op.create_table('evaluacionchofer',
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_table('historialrecargas',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_pasajero', sa.Integer(), nullable=True),
    sa.Column('id_banco', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('numero_referencia', sa.String(), nullable=True),
    sa.Column('monto_recargado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id_banco'], ),
    sa.ForeignKeyConstraint(['id_pasajero'], ['pasajeros.id_pasajero'], ),
    sa.PrimaryKeyConstraint('id_historial'),
    sa.UniqueConstraint('numero_referencia')
    )
    op.create_table('vehiculos',
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('annio', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculos_matricula'), 'vehiculos', ['matricula'], unique=False)
    op.create_table('revisionvehiculo',
    sa.Column('id_revision', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.String(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('fecha_revision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.matricula'], ),
    sa.PrimaryKeyConstraint('id_revision')
    )
    op.create_index(op.f('ix_revisionvehiculo_id_revision'), 'revisionvehiculo', ['id_revision'], unique=False)
    op.create_table('viajes',
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.String(), nullable=True),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('id_pasajero', sa.Integer(), nullable=True),
    sa.Column('duracion', sa.Float(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('lugar_inicio', sa.String(), nullable=False),
    sa.Column('lugar_destino', sa.String(), nullable=False),
    sa.Column('fecha_viaje', sa.Date(), nullable=False),
    sa.Column('estado_viaje', sa.Enum('CANCELADO', 'PAGO', 'EN_ESPERA', 'FINALIZADO', name='estadoviaje'), nullable=False),
    sa.Column('costo_viaje', sa.Float(), nullable=False),
    sa.Column('puntuacion_chofer', sa.Integer(), nullable=True),
    sa.Column('puntuacion_pasajero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.ForeignKeyConstraint(['id_pasajero'], ['pasajeros.id_pasajero'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.matricula'], ),
    sa.PrimaryKeyConstraint('id_viaje')
    )
    op.create_table('pagoschoferes',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('numero_referencia', sa.Integer(), nullable=True),
    sa.Column('monto_cancelado', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id_chofer'], ),
    sa.ForeignKeyConstraint(['id_viaje'], ['viajes.id_viaje'], ),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('numero_referencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagoschoferes')
    op.drop_table('viajes')
    op.drop_index(op.f('ix_revisionvehiculo_id_revision'), table_name='revisionvehiculo')
    op.drop_table('revisionvehiculo')
    op.drop_index(op.f('ix_vehiculos_matricula'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('historialrecargas')
    op.drop_table('evaluacionchofer')
    op.drop_table('datosbancarios')
    op.drop_table('agendacontactos')
    op.drop_table('pasajeros')
    op.drop_table('choferes')
    op.drop_table('usuarios')
    op.drop_table('contactosemergencia')
    op.drop_table('banco')
    # ### end Alembic commands ###
