"""creacion de tablas

Revision ID: 287cf728e31e
Revises: 
Create Date: 2026-06-26 00:21:16.358373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287cf728e31e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('saldo_pendiente', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasajeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo_disponible', sa.Float(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactosemergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('numero_telefonico', sa.String(), nullable=False),
    sa.Column('nombre_contacto', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datosbancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('id_banco', sa.Integer(), nullable=True),
    sa.Column('numero_cuenta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id'], ),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cuenta')
    )
    op.create_table('evaluacionchofer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historialrecargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pasajero', sa.Integer(), nullable=True),
    sa.Column('id_banco', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_referencia', sa.Integer(), nullable=True),
    sa.Column('monto_recargado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id'], ),
    sa.ForeignKeyConstraint(['id_pasajero'], ['pasajeros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_referencia')
    )
    op.create_table('vehiculos',
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('annio', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculos_matricula'), 'vehiculos', ['matricula'], unique=False)
    op.create_table('revisionvehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.String(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisionvehiculo_id'), 'revisionvehiculo', ['id'], unique=False)
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.String(), nullable=True),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('id_pasajero', sa.Integer(), nullable=True),
    sa.Column('duracion', sa.Float(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('lugar_inicio', sa.String(), nullable=False),
    sa.Column('lugar_destino', sa.String(), nullable=False),
    sa.Column('fecha_viaje', sa.Date(), nullable=False),
    sa.Column('estado_viaje', sa.Enum('CANCELADO', 'PAGO', 'EN_ESPERA', name='estadoviaje'), nullable=False),
    sa.Column('costo_viaje', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.ForeignKeyConstraint(['id_pasajero'], ['pasajeros.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagoschoferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_chofer', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('numero_referencia', sa.Integer(), nullable=False),
    sa.Column('monto_cancelado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_chofer'], ['choferes.id'], ),
    sa.ForeignKeyConstraint(['id_viaje'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_referencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagoschoferes')
    op.drop_table('viajes')
    op.drop_index(op.f('ix_revisionvehiculo_id'), table_name='revisionvehiculo')
    op.drop_table('revisionvehiculo')
    op.drop_index(op.f('ix_vehiculos_matricula'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('historialrecargas')
    op.drop_table('evaluacionchofer')
    op.drop_table('datosbancarios')
    op.drop_table('contactosemergencia')
    op.drop_table('pasajeros')
    op.drop_table('choferes')
    op.drop_table('usuarios')
    op.drop_table('banco')
    # ### end Alembic commands ###
