"""fecha evaluacion

Revision ID: f509e7142805
Revises: 65069ecf2a2e
Create Date: 2026-06-29 12:57:06.137012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f509e7142805'
down_revision: Union[str, Sequence[str], None] = '65069ecf2a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluacionchofer', 'fecha_evaluacion',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluacionchofer', 'fecha_evaluacion',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
